name: build website

on:
  push:
    branches: ['main']
    # paths-ignore: ['**.json']
    paths: ['src/**']

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TZ: Asia/Shanghai # 时区

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - run: yarn install
      - run: |
          git pull
          yarn build

      # git diff-index --quiet HEAD || git commit -m 'chore: update by github action'
      - name: Commit GitHub
        run: |
          git config user.name sishenhei7
          git config user.email 982505136@qq.com
          git add .
          git commit --allow-empty -m "chore: update by github action"
          git pull --ff-only
          git push
